title: Danilo Montes' Website
author: Danilo Montes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Project for APCSP
theme: minima

# social links
github_username:  Rubikscrafter # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
